const timelineElements = [
  {
    id: 1,
    title: "Utkarsh Kr. Singh",
    location: "MCKV Institute of Engineering",
    description:
      "react-vertical-timeline-component is available under MIT. See LICENSE for more details.",
    buttonText: "View this",
    date: "January 2023 - january 08:00 AM",
    button1Text: "Rules",
    button2Text: "Register",
    button3Text: "Contact",
    button1Url: "",
    button2Url: "",
    button3Url: "",
    icon: "work",
  },
  {
    id: 1,
    title: "Utkarsh Kr. Singh",
    location: "MCKV Institute of Engineering",
    description:
      "react-vertical-timeline-component is available under MIT. See LICENSE for more details.",
    buttonText: "View this",
    date: "January 2023 - january 08:00 AM",
    button1Text: "Rules",
    button2Text: "Register",
    button3Text: "Contact",
    button1Url: "",
    button2Url: "",
    button3Url: "",
    icon: "work",
  },
  {
    id: 1,
    title: "Utkarsh Kr. Singh",
    location: "MCKV Institute of Engineering",
    description:
      "react-vertical-timeline-component is available under MIT. See LICENSE for more details.",
    buttonText: "View this",
    date: "January 2023 - january 08:00 AM",
    button1Text: "Rules",
    button2Text: "Register",
    button3Text: "Contact",
    button1Url: "",
    button2Url: "",
    button3Url: "",
    icon: "work",
  },
  {
    id: 1,
    title: "Utkarsh Kr. Singh",
    location: "MCKV Institute of Engineering",
    description:
      "react-vertical-timeline-component is available under MIT. See LICENSE for more details.",
    buttonText: "View this",
    date: "January 2023 - january 08:00 AM",
    button1Text: "Rules",
    button2Text: "Register",
    button3Text: "Contact",
    button1Url: "",
    button2Url: "",
    button3Url: "",
    icon: "work",
  },
  {
    id: 1,
    title: "Utkarsh Kr. Singh",
    location: "MCKV Institute of Engineering",
    description:
      "react-vertical-timeline-component is available under MIT. See LICENSE for more details.",
    buttonText: "View this",
    date: "January 2023 - january 08:00 AM",
    button1Text: "Rules",
    button2Text: "Register",
    button3Text: "Contact",
    button1Url: "",
    button2Url: "",
    button3Url: "",
    icon: "work",
  },
  {
    id: 1,
    title: "Utkarsh Kr. Singh",
    location: "MCKV Institute of Engineering",
    description:
      "react-vertical-timeline-component is available under MIT. See LICENSE for more details.",
    buttonText: "View this",
    date: "January 2023 - january 08:00 AM",
    button1Text: "Rules",
    button2Text: "Register",
    button3Text: "Contact",
    button1Url: "",
    button2Url: "",
    button3Url: "",
    icon: "work",
  },
];

export default timelineElements;
