const eventDetails = [
  {
    id: 1,
    name: "Circuit Design",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 2,
    name: "Circuit hello",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 3,
    name: "Circuit Diagram",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 4,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 5,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 6,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 7,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 8,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 9,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 10,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 11,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 12,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 13,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 14,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 15,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
  {
    id: 16,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: "https://meet.google.com/zua-gmya-vyf",
  },
];
export default eventDetails;
