const eventDetails = [
  {
    id: 1,
    name: "Circuit Design",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 2,
    name: "Circuit hello",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 3,
    name: "Circuit Diagram",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 4,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 5,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 6,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 7,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 8,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 9,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 10,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 11,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 12,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 13,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 14,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 15,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
  {
    id: 16,
    name: "Circuit Ddkjsbckjsdn",
    date: "5th January 2023",
    amt: "50",
    size: "1 to 3",
    googlr_Form: "https://forms.gle/14k7Hzp8UC1UCJ839",
    rules: "https://meet.google.com/zua-gmya-vyf",
    contacts: {
      incharge: [{ id: 11, name: "Ms. Sushmita Dey" }],
      SubCommittee: [
        { id: 12, name: "Mr. Sekhar Rana" },
        { id: 13, name: "Mr. Sekhar Rana" },
        { id: 14, name: "Mr. Sekhar Rana" },
        { id: 15, name: "Mr. Sekhar Rana" },
        { id: 16, name: "Mr. Sekhar Rana" },
      ],
      StudentMembers: [
        { id: 17, name: "Ishika Sen ECE", phone: "6289649452", bio: "ECE" },
        { id: 18, name: "Shailee Sharma", phone: "9123709838", bio: "ECE" },
      ],
    },
  },
];
export default eventDetails;
